name: 'release-npm-action'
description: 'Verifies, builds, versions and documents a plugin release to npm.'
inputs:
  NPM_TOKEN:
    description: 'npm Automation token used to publish package.'
    required: true
runs:
  # max available node version, see https://github.com/actions/runner/issues/772
  using: 'node12'
  main: 'index.cjs'
