name: 'release-npm-action'
description: 'Verifies, builds, versions and documents a plugin release to npm.'
author: Matthias Giger
branding:
  icon: 'box'
  color: 'blue'
inputs:
  NPM_TOKEN:
    description: 'npm Automation token used to publish package.'
    required: true
  GITHUB_TOKEN:
    description: 'Used to create GitHub release with changelog contents.'
    required: false
  MANUAL_TRIGGER:
    description: 'Optional release type for manually triggering release workflow.'
    required: false
  CHANNEL:
    description: 'The npm dist-tag for the release, default latest.'
    required: false
  DRY_RUN:
    description: 'Run action for testing puroposes without publishing anything.'
    required: false
  DEBUG:
    description: 'Run semantic-release in debug mode.'
    required: false
outputs:
  version:
    description: 'Version of the release published.'
  channel:
    description: 'dist-tag where the release was published.'
  tag:
    description: 'Name of the git-tag for the new release.'
runs:
  # Action will run with latest node LTS, entry loaded with require() therefore no ESM compatibility.
  # See also https://github.com/actions/runner/issues/772.
  using: 'node12'
  main: 'dist/index.cjs'
